</td>
 <td width="170">
  <center> 
  <?php include("googleads.inc"); ?>
  </center>
 </td>
  </tr>
</table>

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%"><p align="center"><img height="2" src="iamges/line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"></td>
  </tr>
  <tr>
    <td width="100%"><img height="2" src="images/line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"><div align="center"><center><table
    border="0" width="98%" cellspacing="0" cellpadding="0">
      <tr>
        <td style="width: 22%"><font face="Comic Sans MS"><big><strong>PHP and 
		MySQL<br></strong>sample code</big></font></td>
        <td><p align="center"><small>Just examples of <b>PHP</b> code, linking to your <b>MySQL</b>
        database and JavaScript.<br>
        <a href="index.php">1. Home</a> | <a href="thedatabase.php">2. The Database</a> | <a
        href="addauser.php">3. Add a User</a> | <a href="login.php">4. Login</a> | <a
        href="getyourowndbonline.php">5. Get your db online</a></small></td>
      </tr>
    </table>
    </center></div></td>
  </tr>
  <tr>
    <td width="100%"><p align="center"><img height="2" src="images/line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"><br>
    </td>
  </tr>
</table>

<p align="center"><br>
<img height="2" src="images/line.gif" width="730" border="0"><br>
<strong><font color="#000000" face="Verdana">Deltion</font></strong> 
MySQL database en PHP code example site <br>
</p>
</body>
</html>
